import type { ServiceSet, ServiceSetPhotoItem } from "@/lib/service-sets/types";

const BUILT_IN_TIMESTAMP = "2026-01-01T00:00:00.000Z";

function item(
  setId: string,
  presetId: string,
  name: string,
  width: number,
  height: number,
  quantity: number,
  unit: "in" | "mm" = "in",
  allowRotation = false,
): ServiceSetPhotoItem {
  return {
    id: `${setId}-${presetId}`,
    photoSizePresetId: presetId,
    name,
    width,
    height,
    unit,
    quantity,
    allowRotation,
    nameplateEnabled: false,
  };
}

function letterPaper(
  orientation: "portrait" | "landscape" = "portrait",
) {
  return {
    source: "preset" as const,
    presetId: "letter",
    orientation,
    margin: 0.25,
    horizontalSpacing: 0,
    verticalSpacing: 0,
    unit: "in" as const,
  };
}

export const builtInServiceSets: readonly ServiceSet[] = [
  {
    id: "service-set-a",
    name: "Set A",
    description: "Four compact 1 × 1 ID photos.",
    status: "enabled",
    isDefault: true,
    isBuiltIn: true,
    displayOrder: 0,
    price: 40,
    currencyCode: "PHP",
    photoItems: [item("service-set-a", "1x1", "1 × 1", 1, 1, 4)],
    paper: letterPaper(),
    background: { mode: "original" },
    cuttingGuidesEnabled: true,
    sizeLabelsEnabled: false,
    allowPhotoRotation: false,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: "service-set-b",
    name: "Set B",
    description: "Four square 1.5 × 1.5 ID photos.",
    status: "enabled",
    isDefault: false,
    isBuiltIn: true,
    displayOrder: 1,
    price: 40,
    currencyCode: "PHP",
    photoItems: [
      item("service-set-b", "1.5x1.5", "1.5 × 1.5", 1.5, 1.5, 4),
    ],
    paper: letterPaper(),
    background: { mode: "original" },
    cuttingGuidesEnabled: true,
    sizeLabelsEnabled: true,
    allowPhotoRotation: false,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: "service-set-c",
    name: "Set C",
    description: "Four standard 2 × 2 square photos.",
    status: "enabled",
    isDefault: false,
    isBuiltIn: true,
    displayOrder: 2,
    price: 40,
    currencyCode: "PHP",
    photoItems: [item("service-set-c", "2x2", "2 × 2", 2, 2, 4)],
    paper: letterPaper(),
    background: { mode: "solid", color: "#ffffff" },
    cuttingGuidesEnabled: true,
    sizeLabelsEnabled: false,
    allowPhotoRotation: false,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: "service-set-d",
    name: "Set D",
    description: "Mixed compact and square ID package.",
    status: "enabled",
    isDefault: false,
    isBuiltIn: true,
    displayOrder: 3,
    price: 40,
    currencyCode: "PHP",
    photoItems: [
      item("service-set-d", "1x1", "1 × 1", 1, 1, 6),
      item("service-set-d", "2x2", "2 × 2", 2, 2, 2),
    ],
    paper: letterPaper(),
    background: { mode: "original" },
    cuttingGuidesEnabled: true,
    sizeLabelsEnabled: true,
    allowPhotoRotation: false,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: "service-set-e",
    name: "Set E",
    description: "Wallet and 2R studio photo package.",
    status: "enabled",
    isDefault: false,
    isBuiltIn: true,
    displayOrder: 4,
    price: 80,
    currencyCode: "PHP",
    photoItems: [
      item("service-set-e", "wallet", "Wallet", 2.5, 3.5, 2),
      item("service-set-e", "2r", "2R", 2.5, 3.5, 2),
    ],
    paper: {
      source: "preset",
      presetId: "5r",
      orientation: "landscape",
      margin: 0.125,
      horizontalSpacing: 0,
      verticalSpacing: 0,
      unit: "in",
    },
    background: { mode: "original" },
    cuttingGuidesEnabled: true,
    sizeLabelsEnabled: true,
    allowPhotoRotation: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
  {
    id: "service-set-f",
    name: "Set F",
    description: "High-volume mixed-size studio package.",
    status: "enabled",
    isDefault: false,
    isBuiltIn: true,
    displayOrder: 5,
    price: 120,
    currencyCode: "PHP",
    photoItems: [
      item("service-set-f", "1x1", "1 × 1", 1, 1, 12, "in", true),
      item("service-set-f", "1.5x1.5", "1.5 × 1.5", 1.5, 1.5, 8, "in", true),
      item("service-set-f", "2x2", "2 × 2", 2, 2, 6, "in", true),
    ],
    paper: letterPaper(),
    background: { mode: "original" },
    cuttingGuidesEnabled: true,
    sizeLabelsEnabled: true,
    allowPhotoRotation: true,
    createdAt: BUILT_IN_TIMESTAMP,
    updatedAt: BUILT_IN_TIMESTAMP,
  },
] as const;

export function createInitialServiceSets(): ServiceSet[] {
  return builtInServiceSets.map((serviceSet) => ({
    ...serviceSet,
    photoItems: serviceSet.photoItems.map((photoItem) => ({ ...photoItem })),
    paper: { ...serviceSet.paper },
    background: { ...serviceSet.background },
  }));
}
